version: '3'
services:
  app:
    image: minifier
    restart: always
    container_name: minifier
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - net
    volumes:
      - "/opt:/app/storage"
    env_file:
      - backend.env
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis
    restart: always
    container_name: redis
    volumes:
      - /var/parspack/redis:/data
    networks:
      - net

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - /var/parspack/mongodb:/data/db
    networks:
      - net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
  
  web-server:
    image: openresty
    build: 
      context: ./web-server
      dockerfile: Dockerfile
    container_name: openresty
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./web-server/scripts:/usr/local/openresty/nginx/scripts
      - openresty-logs:/usr/local/openresty/nginx/logs
    command: openresty -g 'daemon off;'
    networks:
      - net

volumes:
  openresty-logs:
networks:
  net:


